use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
target 'MediaUtils_Example' do
  pod 'MediaUtils', :path => '../'

  target 'MediaUtils_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
    
     pod 'NFAToolkit'
  end
end
